module.exports.bookService=require('./book.service')
module.exports.customerService = require('./customer.service')
module.exports.roomTypeService = require('./roomType.service')
module.exports.roomService = require('./room.service')
module.exports.contactService = require('./contact.service')
